/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
export var styles = ['p[_ngcontent-%COMP%] {\n  color: red;\n}'];
//# sourceMappingURL=app.component.css.shim.ngstyle.js.map